# Generated by Django 3.2.10 on 2022-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_rename_topic_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choose',
            field=models.BooleanField(default=False),
        ),
    ]
