# Generated by Django 3.2.10 on 2022-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20220203_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
